console:
  config:
    kafka:
      brokers:
        - kafka-kafka-bootstrap.kafka.svc.cluster.local:9092

ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - host: redpanda.vamseekonda.com
      paths:
        - path: /
          pathType: Prefix
