apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: manifest-addons
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/VamKon/home-lab-deploy.git
        revision: HEAD
        files:
          - path: "addons/*/manifest.yaml"
  template:
    metadata:
      name: "{{name}}"
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
      annotations:
        argocd.argoproj.io/sync-wave: "{{syncWave}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/VamKon/home-lab-deploy.git
        targetRevision: HEAD
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
